let bandas = { 
    lista: [
        {
        nombre: "ACDC",
        integrantes: 5,
        genero: "rock",
        topCanciones: ["Highway to hell","Back in Black", "Thunderstruck"],
        cover:"",
        id:1,
        video:"",
        },
        {
        nombre: "Metallica",
        integrantes: 5,
        genero: "rock",
        topCanciones: ["Enter Sandman","Back in Black","Thunderstruck"],
        cover:"",
        id:2,
        video:"",
        },
        {
        nombre: "Daddy yankee",
        integrantes: 1,
        genero: "reggeaton",
        topCanciones: ["Dura","Con Calma", "Pose"],
        cover:"",
        id:3,
        video:"",
        },
        {
        nombre: "J Balvin",
        integrantes: 1,
        genero: "reggeaton",
        topCanciones: ["Rojo","Azul","Blanco"],
        cover:"",
        id:4,
        video:"",
        },
        {
        nombre: "Justin Bieber",
        integrantes: 1,
        genero: "pop",
        topCanciones: ["Yummy","Baby", "Intentions"],
        cover:"",
        id:5,
        video:"",
        },
        {
        nombre: "Lady Gaga",
        integrantes: 1,
        genero: "rock",
        topCanciones: ["Shallow","Bad Romance","Rain on me"],
        cover:"",
        id:6,
        video:"",
        },
        {
        nombre: "Sticky fingers",
        integrantes: 5,
        genero: "indie",
        topCanciones: ["Liquorlip loaded gun","Cool & Calm", "Australia street"],
        cover:"",
        id:7,
        video:"",
        },
        {
        nombre: "Masego",
        integrantes: 1,
        genero: "indie",
        topCanciones: ["Tadow","Navajo","Queen tings"],
        cover:"",
        id:8,
        video:"",
        },
        {
        nombre: "Eminem",
        integrantes: 1,
        genero: "rap",
        topCanciones: ["Lose yourself","Rap god", "Godzilla"],
        cover:"",
        id:9,
        video:"",
        },
        {
        nombre: "Da Baby",
        integrantes: 5,
        genero: "rap",
        topCanciones: ["Rockstar","BOP","Suge"],
        cover:"",
        id:10,
        video:"",
        },
     

    ]}

    module.exports = bandas